### ISSUE TITLE
Can you give some minimal docs or examples

### ISSUE THREAD

**Issue by jfeltkamp** [duartegarin/graphql_webform#2]
Can you give some minimal docs or examples, how to query a webform?  Does it work inside the drupal/graphql Module and does it use the "/graphql"-Endpoint?

**Comment by duartegarin** [comment]
Hi @jfeltkamp ,

This repo is a work in progress (proof of concept) and it's not production ready.
It does function alongside the GraphQL module and exposes a few fields in order to retrieve webform definitions.

You can use the WebformById field and inside the webform elements to obtain a JSON representation of your webform definition.
That's as far as I got before I had to move on to other things.
 
I have a project in a few months that will likely need this so will continue then, but feel free to send PRs through if you want to help develop.

Cheers

**Comment by jfeltkamp** [comment]
Thanks for your reply (and sorry for my multi-channel alarm). For the current project I decided to use the REST API with the "Webform REST" module. But I don't like that mix of GraphQL and REST. In on of the next projects I will go in the deep of the GraphQL interface and then I would love to help. It's a very interesting task.
