### ISSUE TITLE
Future of this Module ? 

### ISSUE THREAD

**Issue by zuernBernhard** [duartegarin/graphql_webform#5]
Will this become available on drupal.org ? 

Do you plan to Support Mutations to create Webform submissions ?

**Comment by duartegarin** [comment]
Hi @zuernBernhard ,
Thank you for your question and apologies for the main reply.

To answer your question, yes this module will become available on drupal.org although development will always be done in Github (similarly to what happened with my other graphql module "GraphQL Search API".

At the moment this module is being actively developed by Prosple and we should have an alpha release pretty soon which will likely tie into when we start using this in production for our platform.

Although I started this way back (before we actually needed it), @carolpettirossi is championing the development for this and so she probably will become the lead maintainer (it's in this repo just because it was easier to continue developing what I started).

As for mutations, yes we actually already use mutations, @carolpettirossi have they made way into this module or being kept in our custom codebase?

Cheers,
Duarte

**Comment by carolpettirossi** [comment]
Hi @zuernBernhard, 

Yes, we do support mutations. Currently, it's available only on the dev branch, but as @duartegarin mentioned it will be available soon as an alpha version. 

You can read about the webform submission mutation here: https://github.com/duartegarin/graphql_webform/blob/dev/README.md#create-a-webform-submission

Cheers,
Carol

**Comment by zuernBernhard** [comment]
That sounds great. Thank you !
